### PR TITLE
Switch to PDF.js and add click-to-scroll support

### LINKED ISSUE #20: Use SVG rather than PNG
Reason is pretty obvious.

### PR DESCRIPTION
**Pull request by TimothyGu**
My fork of PDF.js is loaded via a Git submodule. Changes can be browsed through https://github.com/mozilla/pdf.js/compare/master...TimothyGu:master

<del>Right now, this doesn't work on iOS because of some MIME-type issues for the PDFs (I believe). I'll try to fix it after this PR is merged.</del> Nope, it's about cross-domain redirects. Fixed.

Fixes #20, #41, #48.

### CODE REVIEW

**Comment by TimothyGu** [comment]
Quick demo: https://youtu.be/VM8Tl_JtjZQ

**Comment by scottlinux** [comment]
Looks awesome - will this work on mobile?

**Comment by trevordixon** [comment]
Very well done! It looks really good. Merge and deploy that.

**Comment by TimothyGu** [comment]
@scottlinux Yes!

**Pull request merged**
