### PR TITLE
Switch to Bootstrap

### LINKED ISSUE #13: Lilybin on Android phone
Hi,

Thanks for this great tool, I can work with Lilypond everywhere. But i have a problem on my 5 inch Android phone with Chrome Browser : I've no access to the code panel because of the size of the preview panel that I cannot reduce . The best will be to have a button at right to hide/show preview panel and a button at left to hide/show dropbox panel.

Christophe

### PR DESCRIPTION
**Pull request by TimothyGu**
Not ready to be merged yet. Will fix #13, #19, and #20. #14 and #25 will be easier to fix afterwards.

TODO:
- [x] better dropdown menu styles
- [x] better navbar hover/active styles
- [x] tweak navbar for small screen devices
- [x] completely mobilize
- [ ] integrate svg-pan-zoom
- [x] cleanup preview toolbar

### CODE REVIEW

**Comment by trevordixon** [comment]
Looking good so far! Much improved.

**Comment by TimothyGu** [comment]
Ok finished this thing. iPhone/extraextrasmallscreen device still needs improvement, but it's perfectly usable on my Nexus 7 now. (Excluding preview scrolling)

iPhone 5s

**Comment by TimothyGu** [comment]
Nexus 7

**Comment by TimothyGu** [comment]
desktop1

**Comment by scottlinux** [comment]
Is it possible to change the drop down 'LilyPond Stable/LilyPond Unstable' to just say 'Stable/Unstable'? Otherwise the nav is too large for mobile devices.

Or if there is a way to have this occur only on small mobile device that would be awesome.

**Comment by TimothyGu** [comment]
@scottlinux fixed in b7874fe

**Pull request merged**
